AWSTemplateFormatVersion: 2010-09-09

Description: Creates an OIDC provider for GitHub Actions

Parameters:
  GitHubOrganization:
    Type: String
    Description: The GitHub organization name
  GitHubRepository:
    Type: String
    Description: The GitHub repository name

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: "https://token.actions.githubusercontent.com"
      ClientIdList:
        - "sts.amazonaws.com"

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "GitHubActionsRole"
      Description: "Role for GitHub Actions to assume"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              {
                "Federated": !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com",
              }
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub": !Sub "repo:${GitHubOrganization}/${GitHubRepository}"
